creación de clase solicitud
lucast086/serviciosYA pull request #35
Opened 2023-07-04 18:36 UTC by IssaGrey

ok

2023-07-05 22:16 UTC, lucast086 requested changes

2023-07-05 22:16 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/SolicitudServicio.java
> +    public void crearSolicitud(Cliente cliente, String idProveedor, String descripcion, Estado estado, float costo, String comentario, Date fechaServicio)throws Exepcion{
deberia de llegar un id de cliente y en el metodo se deberia buscar el cliente a traves de cliente servicio, igual que con el proveedor

2023-07-05 22:16 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/SolicitudServicio.java
> +    public void modificarById (String id, Cliente cliente,String idProveedor, String descripcion, Estado estado, float costo, String comentario, Date fechaServicio) throws Exepcion {
deberia de llegar un Objeto proveedor, no solamente el id

2023-07-10 17:58 UTC, lucast086 requested changes
Son varios cambios, te pido que vayas escribiendo en cada recuadro un a respuesta cada vez que completes un cambio
ejemplo de respuesta: 
 Corregido! (aclaracion opcional)

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ClienteControlador.java
> +    public String modificarCliente (@PathVariable String id, @RequestParam String nombre, @RequestParam String apellido, @RequestParam String direccion, @RequestParam String email, @RequestParam Stri
las solicitudes no son datos del cliente que deban ser modificados por el mismo. ese parametro no deberia ir

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> -    public String registro(RedirectAttributes redirectAttributes, @RequestParam String nombre, @RequestParam String apellido, @RequestParam String email, @RequestParam String telefono, @RequestParam
@RequestParam List solicitudes

cuando se crea un proveedor no va a tener solicitudes por lo que no deben ser pasadas por el front, asique ese atributo no debe ir

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> +            proveedorServicio.crear(nombre,apellido,email,telefono,password,password2,imagen,oficios, Rol.PROVEEDOR, solicitudes);
no deberia pasarse el argumento solicitudes

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> +            proveedorServicio.modificarByID(id, nombre, apellido, email, telefono, password, password2, imagen, oficios, solicitudes);
no deberia pasarse el argumento solicitudes

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> +    public String modificarProveedor (@PathVariable String id, @RequestParam String nombre, @RequestParam String apellido, @RequestParam String email, @RequestParam String telefono, @RequestParam Str
las solicitudes no son datos del proveedor que deban ser modificados por el mismo. ese parametro no deberia ir

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/entidades/Oficio.java
> +<<<<<<< HEAD
tenes un merge sin resolver IMPORTANTE

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ClienteServicio.java
> +    public void crear(String nombre, String apellido,String direccion, String email, String telefono, String password,String password2,Rol rol, List<Solicitud> solicitudes) throws Exepcion {
no deberia tener ese párametro List<Solicitud> solicitudes

deberias crear una lista de vacia de solicitudes y agregarsela al cliente

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ClienteServicio.java
> +    public void modificarById (String id,String nombre, String apellido,String direccion, String email, String telefono, String password,String password2, List<Solicitud> solicitudes) throws Exepcion
List<Solicitud> solicitudes no deberia recibir este parametro

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ClienteServicio.java
> +        cliente.setSolicitudes(solicitudes);
no deben editarse las solicitudes

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ProveedorServicio.java
> +    public void crear(String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios, Rol rol,List<Solicitud> solicitudes
no deberia tener ese párametro List solicitudes

deberias crear una lista de vacia de solicitudes y agregarsela al proveedor

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ProveedorServicio.java
> +    public void modificarByID(String id, String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios,List<Solicitud> s
no deben editarse las solicitudes

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ProveedorServicio.java
> +        proveedor.setSolicitudes(solicitudes);
no deben editarse las solicitudes

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/SolicitudServicio.java
> +        solicitud.setId(id);
EL ID no debe volver a setearse solo se usa para buscar la solicitud

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IClienteServicio.java
> +     void crear(String nombre, String apellido, String email, String telefono, String direccion, String password, String password2,Rol rol,List<Solicitud> solicitudes) throws Exepcion;
List<Solicitud> solicitudes no debe estar el parametro

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IClienteServicio.java
> +     void modificarById (String id,String nombre, String apellido, String email, String telefono,String direccion, String password,String password2,List<Solicitud> solicitudes) throws Exepcion;
List<Solicitud> solicitudes  no debe estar el parametro

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IProveedorServicio.java
> +    void crear(String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios, Rol rol,List<Solicitud> solicitudes) throw
List<Solicitud> solicitudes  no debe estar el parametro

2023-07-10 17:58 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IProveedorServicio.java
> +    void modificarByID(String id,String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios, List<Solicitud> solicitu
List<Solicitud> solicitudes  no debe estar el parametro

2023-07-10 23:36 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> -    public String registro(RedirectAttributes redirectAttributes, @RequestParam String nombre, @RequestParam String apellido, @RequestParam String email, @RequestParam String telefono, @RequestParam
Corrección realizada

2023-07-10 23:37 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> +            proveedorServicio.crear(nombre,apellido,email,telefono,password,password2,imagen,oficios, Rol.PROVEEDOR, solicitudes);
corrección realizada

2023-07-10 23:43 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/entidades/Oficio.java
> +<<<<<<< HEAD
merge resuelto en la clase oficio y proveedor controlador

2023-07-10 23:47 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> +            proveedorServicio.modificarByID(id, nombre, apellido, email, telefono, password, password2, imagen, oficios, solicitudes);
se quita el argumento solicitudes.

2023-07-11 00:00 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ClienteControlador.java
> +    public String registro(RedirectAttributes redirectAttributes, @RequestParam String nombre,@RequestParam String apellido,@RequestParam String direccion,@RequestParam String email,@RequestParam Str
se quita el atributo lista de solicitudes

2023-07-11 00:03 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ClienteControlador.java
> +            clienteServicio.crear(nombre,apellido,direccion,email,telefono,password,password2,Rol.USER, solicitudes);
corregido ..

2023-07-11 00:04 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ClienteControlador.java
> +    public String modificarCliente (@PathVariable String id, @RequestParam String nombre, @RequestParam String apellido, @RequestParam String direccion, @RequestParam String email, @RequestParam Stri
corrección realizada

2023-07-11 00:05 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ClienteControlador.java
> +            clienteServicio.modificarById(id,nombre,apellido,email,telefono,direccion,password,password2,solicitudes);
corrección realizada

2023-07-11 00:08 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/controladores/ProveedorControlador.java
> +    public String modificarProveedor (@PathVariable String id, @RequestParam String nombre, @RequestParam String apellido, @RequestParam String email, @RequestParam String telefono, @RequestParam Str
se quita el parámetro del método modificar.

2023-07-11 00:11 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ClienteServicio.java
> +    public void crear(String nombre, String apellido,String direccion, String email, String telefono, String password,String password2,Rol rol, List<Solicitud> solicitudes) throws Exepcion {
retiro el parámetro   List solicitudes e la Interfaz ClienteServicio

2023-07-11 00:14 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ClienteServicio.java
> +    public void modificarById (String id,String nombre, String apellido,String direccion, String email, String telefono, String password,String password2, List<Solicitud> solicitudes) throws Exepcion
se quita List solicitudes de ClienteServicio

2023-07-11 00:15 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ClienteServicio.java
> +        cliente.setSolicitudes(solicitudes);
se retira setSolicitudes, en el metodo modificar Cliente

2023-07-11 00:36 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ProveedorServicio.java
> +    public void crear(String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios, Rol rol,List<Solicitud> solicitudes
se elimina el parametro  List solicitudes de crear proveedor 

**PENDIENTE  crear una lista de vacia de solicitudes y agregarsela al proveedor**

2023-07-11 00:38 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/ProveedorServicio.java
> +    public void modificarByID(String id, String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios,List<Solicitud> s
SE QUITA PARAMETRO DE LIST SOLICITUD DE MODIFICAR PROVEEDOR

2023-07-11 00:56 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/SolicitudServicio.java
> +        solicitud.setId(id);
Se quita el set de modificar proveedor

2023-07-11 00:59 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IClienteServicio.java
> +     void crear(String nombre, String apellido, String email, String telefono, String direccion, String password, String password2,Rol rol,List<Solicitud> solicitudes) throws Exepcion;
corrección realizada

2023-07-11 01:02 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IClienteServicio.java
> +     void modificarById (String id,String nombre, String apellido, String email, String telefono,String direccion, String password,String password2,List<Solicitud> solicitudes) throws Exepcion;
corrección realizada

2023-07-11 01:03 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IProveedorServicio.java
> +    void crear(String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios, Rol rol,List<Solicitud> solicitudes) throw
corrección realizada.

2023-07-11 01:03 UTC, IssaGrey commented on serviciosYa/src/main/java/com/serviciosYa/servicios/interfaces/IProveedorServicio.java
> +    void modificarByID(String id,String nombre, String apellido, String email, String telefono, String password, String password2, MultipartFile imagen, List<Oficio> oficios, List<Solicitud> solicitu
corrección realizada.

2023-07-11 02:27 UTC, lucast086 approved these changes

2023-07-11 02:27 UTC, merged