Implementación de interfaz de servicio de usuario
lucast086/serviciosYA pull request #5
Opened 2023-06-18 19:24 UTC by Nahuel-Galera

2023-06-18 21:13 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    private UsuarioRepositorio ur;
usar nombres descriptivos en las variables por ejemplo usuarioRepostorio

2023-06-18 21:13 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +public class UsuarioServicio {
deberia implementar una interfaz para mejorar la calidad de codigo.

2023-06-18 21:15 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        validar(nombre,apedillo,email,telefono,password,password2);
pequeño error en el nombre apedillo, deberia ser apellido

2023-06-18 21:15 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void crear(String nombre, String apedillo, String email, String telefono, String password,String password2, Boolean activo) throws Exception {
pequeño error en el nombre apedillo, deberia ser apellido

2023-06-18 21:15 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        usuario.setApellido(apedillo);
pequeño error en el nombre apedillo, deberia ser apellido

2023-06-18 21:41 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    @Transactional
eliminar metodo

2023-06-18 21:42 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void modificarByNombreAndApedillo (String nombre, String apedillo, String email, String telefono, String password,String password2, Boolean activo) throws Exception {
eliminar metodo

2023-06-18 21:44 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarByEmail (String email){
eliminar este metodo

2023-06-18 21:44 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarByNombreAndApedillo (String nombre, String apedillo){
eliminar este metodo

2023-06-18 21:48 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarById (String id){
Luego de buscar el usuario, debo controlar si existe o no, en caso negativo debo arrojar una excepcion. en caso afirmativo debo eliminar el usuario.

la variable confirmar no prodcce ningun efecto.

2023-06-18 21:50 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
Se puede usar un orElseThrow para devolver una excepcion en caso negativo

2023-06-18 21:52 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
Se puede usar un orElseThrow para devolver una excepcion en caso negativo

2023-06-18 21:52 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
Se puede usar un orElseThrow para devolver una excepcion en caso negativo

2023-06-18 21:55 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarById (String id){
la variable confirmar no tiene ningun efecto.

La eliminacion se hace modificando el atributo Activo en False.
y guardando en la base de datos el usuario con el atributo modificado.

2023-06-18 21:55 UTC, lucast086 requested changes
hay varias modificaciones principalmente controla en todo el documento la palabra apedillo

2023-06-18 23:01 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    private UsuarioRepositorio ur;
Corregido

2023-06-18 23:01 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +public class UsuarioServicio {
Corregido

2023-06-18 23:01 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        validar(nombre,apedillo,email,telefono,password,password2);
Corregido

2023-06-18 23:01 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void crear(String nombre, String apedillo, String email, String telefono, String password,String password2, Boolean activo) throws Exception {
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        usuario.setApellido(apedillo);
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        usuario.setApellido(apedillo);
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    @Transactional
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void modificarByNombreAndApedillo (String nombre, String apedillo, String email, String telefono, String password,String password2, Boolean activo) throws Exception {
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarByEmail (String email){
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarByNombreAndApedillo (String nombre, String apedillo){
Corregido

2023-06-18 23:02 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
Corregido

2023-06-18 23:03 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
Corregido

2023-06-18 23:07 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
Corregido

2023-06-18 23:12 UTC, Nahuel-Galera commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +    public void eliminarById (String id){
corregido

2023-06-19 16:41 UTC, lucast086 commented on serviciosYa/src/main/java/com/serviciosYa/servicios/UsuarioServicio.java
> +        if (repuesta.isPresent()){
la creacion del usuario nuevo y el if ya no seran necesarios al usar orElseThrow

2023-06-19 16:46 UTC, lucast086 requested changes
un solo cambio y estamos, eliminar unas lineas en buscarByNombreAndApeliido

2023-06-19 22:50 UTC, lucast086 approved these changes
todo ok

2023-06-19 22:51 UTC, merged